[project]
authors = ["Kada-quantum <kada02ak1@outlook.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "osdr-visualizer"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.7,<4"
ollama-python = ">=0.3.3,<0.4"
flask = ">=3.0.3,<4"
requests = ">=2.32.3,<3"
